sonar.projectKey=LuisGaravaso_fc3-sonar-ci-js
sonar.organization=luisgaravaso


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=fc3-sonar-ci-js
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Source directory
sonar.sources=src
sonar.exclusions=**/*.test.js,**/node_modules/**

# Tests directory
sonar.tests=src
sonar.test.inclusions=**/*.test.js

# Code coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js